### ISSUE TITLE
这个是直接把Revel的东西拷过来就能用么？

### ISSUE THREAD

**Issue by kenshinji** [TimothyYe/gocasts#1]
为什么README.MD里面基本就是讲Revel的？？

**Comment by kenshinji** [comment]
好吧，才发现你的vim-tips.com跟gocast.net外观如此相似...

**Comment by TimothyYe** [comment]
呃……
README还没来得及更新
两个站比较相似，直接复制了一些样式过来，不过底层有些不一样。
Vim-Tips.com是基于Martini的，GoCasts是基于Revel的。
